name: Deploy NextJs App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency: 
      group: Deploy
      cancel-in-progress: true
      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Install Dependencies
        run: npm install
      - name: Build Next.Js
        run: npm run build
      - name: Deploy App
        run: echo "Deploying app"
        

    
